export const SITE = {
  name: 'Octopai',
  domain: 'octopai.it',
  tagline: 'Everything you need to set up, run, and optimize AI agents.',
  description:
    'The all-in-one platform for training, deploying, and managing AI agents. From zero to revenue in 28 days.',
  version: 'v1.0',
  email: 'hello@octopai.it',
  twitter: '@octopai_it',
} as const;

export const NAV_LINKS = [
  { label: 'How It Works', href: '#how-it-works' },
  { label: 'Phases', href: '#phases' },
  { label: 'Agent Hub', href: '/agents' },
  { label: 'Training', href: '/training' },
  { label: 'Pricing', href: '/pricing' },
] as const;

export const PHASES = [
  {
    id: 1,
    name: 'Foundation',
    days: '1-4',
    color: 'green',
    description: 'Set up your agent architecture, define SOUL.md, configure memory systems.',
    lessons: ['Agent Architecture 101', 'SOUL.md Setup', 'Memory & Context', 'Security Config'],
  },
  {
    id: 2,
    name: 'Execute',
    days: '5-10',
    color: 'blue',
    description: 'Run your first experiments. Test product ideas, validate demand.',
    lessons: [
      'Experiment Menu',
      'Market Research Agent',
      'Content Generation',
      'Product Prototype',
      'Validation Loop',
      'Iterate & Refine',
    ],
  },
  {
    id: 3,
    name: 'Distribute',
    days: '11-15',
    color: 'purple',
    description: 'Set up distribution channels. Get your agent products in front of buyers.',
    lessons: [
      'Channel Strategy',
      'Marketplace Setup',
      'Social Distribution',
      'SEO & Discovery',
      'Outreach Automation',
    ],
  },
  {
    id: 4,
    name: 'Product',
    days: '16-20',
    color: 'orange',
    description: 'Build production-ready products. Polish, price, and package.',
    lessons: [
      'Product Refinement',
      'Pricing Strategy',
      'Landing Pages',
      'Payment Integration',
      'Launch Checklist',
    ],
  },
  {
    id: 5,
    name: 'Launch',
    days: '21-24',
    color: 'green',
    description: 'Go live. Launch your agent products and start collecting revenue.',
    lessons: ['Launch Day', 'Feedback Loop', 'Optimization', 'Scale Prep'],
  },
  {
    id: 6,
    name: 'Revenue Sprint',
    days: '25-28',
    color: 'blue',
    description: 'Maximize revenue. Optimize funnels, add products, scale what works.',
    lessons: ['Revenue Analysis', 'Upsell Systems', 'Automation Scale', 'Next Steps'],
  },
] as const;

export const AGENT_CATEGORIES = [
  { id: 'content', label: 'Content', icon: '📝' },
  { id: 'research', label: 'Research', icon: '🔍' },
  { id: 'sales', label: 'Sales', icon: '💰' },
  { id: 'support', label: 'Support', icon: '🛟' },
  { id: 'dev', label: 'Development', icon: '⚡' },
  { id: 'data', label: 'Data', icon: '📊' },
  { id: 'marketing', label: 'Marketing', icon: '📣' },
  { id: 'automation', label: 'Automation', icon: '🤖' },
] as const;

export const FEATURED_AGENTS = [
  {
    id: 'atlas-forge',
    name: 'Atlas Forge',
    handle: '@AtlasForge',
    category: 'content',
    description: 'Generative art agent. Creates collections, manages drops, handles marketplace distribution.',
    revenue: '$2.5K/mo',
    rating: 4.8,
    sales: 340,
    tags: ['art', 'nft', 'creative'],
    status: 'active',
  },
  {
    id: 'juno-agent',
    name: 'Juno',
    handle: '@JunoAgent',
    category: 'automation',
    description: 'Zero Human Company builder. Sets up autonomous business operations end-to-end.',
    revenue: '$27K/mo',
    rating: 4.9,
    sales: 890,
    tags: ['business', 'automation', 'ops'],
    status: 'active',
  },
  {
    id: 'felix-craft',
    name: 'Felix Craft',
    handle: '@FelixCraft',
    category: 'sales',
    description: 'AI persona builder. Creates and sells agent skills on marketplace.',
    revenue: '$78K+',
    rating: 4.0,
    sales: 940,
    tags: ['skills', 'marketplace', 'persona'],
    status: 'active',
  },
  {
    id: 'data-scout',
    name: 'Data Scout',
    handle: '@DataScout',
    category: 'research',
    description: 'Market research agent. Scrapes, analyzes, and reports on market trends.',
    revenue: '$4.2K/mo',
    rating: 4.6,
    sales: 210,
    tags: ['research', 'analysis', 'trends'],
    status: 'active',
  },
  {
    id: 'pixel-smith',
    name: 'Pixel Smith',
    handle: '@PixelSmith',
    category: 'content',
    description: 'Design automation agent. Generates thumbnails, social assets, brand kits.',
    revenue: '$8.1K/mo',
    rating: 4.7,
    sales: 560,
    tags: ['design', 'graphics', 'branding'],
    status: 'active',
  },
  {
    id: 'copy-ghost',
    name: 'Copy Ghost',
    handle: '@CopyGhost',
    category: 'marketing',
    description: 'Copywriting agent. Writes emails, ads, landing pages that convert.',
    revenue: '$12K/mo',
    rating: 4.5,
    sales: 720,
    tags: ['copy', 'email', 'ads'],
    status: 'active',
  },
] as const;

export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    period: 'forever',
    description: 'Get started with AI agents',
    features: [
      'Access to 5 free agent templates',
      'Community forum access',
      'Basic training (Days 1-4)',
      'Agent architecture guide',
      'Email support',
    ],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 197,
    period: 'one-time',
    description: 'Full access to everything',
    features: [
      'All 28-day training modules',
      'Full Agent Hub access (50+ agents)',
      'Experiment Menu (16 recipes)',
      'Idea Generator (300+ ideas)',
      'Architecture Bundle',
      'Private community access',
      'Revenue tracking dashboard',
      'Priority support',
      'Lifetime updates',
    ],
    cta: 'Get Full Access',
    highlighted: true,
  },
  {
    id: 'team',
    name: 'Team',
    price: 497,
    period: 'one-time',
    description: 'For teams building with agents',
    features: [
      'Everything in Pro',
      'Up to 5 team members',
      'Team agent workspace',
      'Shared experiment tracking',
      'Custom agent templates',
      'Dedicated onboarding call',
      'Slack support channel',
    ],
    cta: 'Get Team Access',
    highlighted: false,
  },
] as const;

export const FAQ_ITEMS = [
  {
    q: 'What is Octopai?',
    a: 'Octopai is an all-in-one platform for setting up, training, and optimizing AI agents. Our 28-day program takes you from zero to revenue-generating agents, and our Agent Hub gives you access to pre-built agents and templates.',
  },
  {
    q: 'Do I need coding experience?',
    a: 'No. Each lesson has a "Human" mode (manual steps) and a "Machine" mode (copy-paste prompts). If your agent has file system access, most steps run automatically.',
  },
  {
    q: 'Which AI models are supported?',
    a: 'Octopai works with Claude, GPT-4, Gemini, and other major LLMs. The architecture is model-agnostic — you bring your own API key.',
  },
  {
    q: 'How long does the training take?',
    a: "The program is designed for 28 days, but you can go faster. Each day takes 15-30 minutes of human input. Your agent does the heavy lifting.",
  },
  {
    q: 'What kind of revenue can I expect?',
    a: 'Results vary. Our case studies show agents generating $2.5K to $78K+. The key is choosing the right experiment and iterating based on market feedback.',
  },
  {
    q: 'Is the Agent Hub a marketplace?',
    a: 'Yes. You can browse, use, and eventually sell your own agent templates. Think of it as an app store for AI agents.',
  },
  {
    q: 'What if I already have agents running?',
    a: 'Great. Skip to the phases that matter. The training is modular — use the Experiment Menu and Hub without doing every lesson.',
  },
  {
    q: 'Can I get a refund?',
    a: 'Yes. 30-day money-back guarantee, no questions asked.',
  },
] as const;
